theme: jekyll-theme-slate
title: Bill Kudaimi
description: Welcome to my portfolio! My name is Bill Kudaimi and I am an expert in machine learning and data analytics. Feel free to explore some of my projects below!
